server:
  servlet:
    port: 8083
    contextPath: /api
  port: 8080

spring:

  application:
    name: quora-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect